language: php

matrix:
  include:
    #- php: 5.3
    #  dist: precise
    #- php: 5.3
    #  dist: precise
    #  env: DEPENDENCIES=low
    #- php: 5.4
    #  dist: trusty
    #- php: 5.4
    #  dist: trusty
    #  env: DEPENDENCIES=low
    #- php: 5.5
    #  dist: trusty
    #- php: 5.5
    #  dist: trusty
    #  env: DEPENDENCIES=low
    #- php: 5.6
    #- php: 5.6
    #  env: DEPENDENCIES=low
    #- php: 7.0
    #- php: 7.0
    #  env: DEPENDENCIES=low
    #- php: 7.1
    #- php: 7.1
    #  env: DEPENDENCIES=low
    #- php: 7.2
    ## Could be enabled when we'll upgrade PHPUnit
    ## - php: 7.2
    ##   env: DEPENDENCIES=low
    #- php: 7.3
    #  env: COVERAGE=true
    ## Could be enabled when we'll upgrade PHPUnit
    ## - php: 7.3
    ##   env: DEPENDENCIES=low
    #- php: 7.4
    - php: nightly
    #- php: 5.3
    #  dist: precise
    #  env: BUILD_PHAR=true
    #- php: 7.3
    #  env: WEBSITE=true
  fast_finish: true

sudo: false

env:
  global:
    TEST_CONFIG="phpunit.xml.dist"


before_script:
  - phpenv config-rm xdebug.ini || echo "XDebug is not enabled"
  - composer self-update
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-dist --prefer-lowest --prefer-stable; fi
  - if [ "$DEPENDENCIES" != "low" ]; then composer update --prefer-dist --prefer-stable --ignore-platform-reqs; fi

script:
  - if [[ $WEBSITE != 'true' && $BUILD_PHAR != 'true' && $COVERAGE != 'true' ]]; then vendor/bin/phpunit --configuration $TEST_CONFIG --colors; fi
  - if [[ $WEBSITE != 'true' && $BUILD_PHAR != 'true' && $COVERAGE = 'true' ]]; then phpdbg -qrr vendor/bin/phpunit --configuration $TEST_CONFIG --colors --coverage-text --coverage-clover=coverage.xml; fi
  - if [[ $WEBSITE = 'true' ]]; then composer build-website; fi
  - |
    if [[ $BUILD_PHAR = 'true' ]]; then
      git submodule update --init &&
      ant package -D-phar:filename=./pdepend.phar &&
      ./pdepend.phar --version
    fi

after_script:
  - |
    if [[ -f coverage.xml ]]; then
      bash <(curl -s https://codecov.io/bash) -f coverage.xml
      wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi

notifications:
  irc: "irc.freenode.org#pdepend"

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/website
    on:
      branch: master
      condition: $WEBSITE
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: pdepend.phar
    skip_cleanup: true
    on:
      tags: true
      repo: pdepend/pdepend
      condition: "$BUILD_PHAR"

addons:
  snaps:
    - name: ant
      classic: true
