language: php

#php:
#    - 5.3
#    - 5.4
#    - 5.5
#    - 5.6
#    - 7.0
#    - hhvm
#    - hhvm-nightly

matrix:
    include:
        - php: 5.3
          env: DEPENDENCIES=low
        - php: 5.4
          env: DEPENDENCIES=low
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
#        - php: hhvm-nightly
    fast_finish: true

env:
    global:
        TEST_CONFIG="phpunit.xml.dist"

before_script:
    - composer self-update
    - if [ $DEPENDENCIES = low ] ; then composer update --prefer-dist --prefer-lowest --prefer-stable ; fi
    - if [ ! $DEPENDENCIES ] ; then composer update --prefer-dist ; fi
    - composer install

script:
    - if [ $TRAVIS_PHP_VERSION != 7.0 ]; then vendor/phpunit/phpunit/phpunit --configuration $TEST_CONFIG --colors ; fi
    - if [ $TRAVIS_PHP_VERSION  = 7.0 ]; then vendor/phpunit/phpunit/phpunit --configuration $TEST_CONFIG --colors --coverage-text ; fi
#    - if [ $TRAVIS_PHP_VERSION != 5.6 ] && [ $TRAVIS_PHP_VERSION != 7.0 ]; then vendor/phpunit/phpunit/phpunit --configuration $TEST_CONFIG --colors ; fi
#    - if [ $TRAVIS_PHP_VERSION  = 5.6 ] || [ $TRAVIS_PHP_VERSION  = 7.0 ]; then vendor/phpunit/phpunit/phpunit --configuration $TEST_CONFIG --colors --coverage-text ; fi

notifications:
    irc: "irc.freenode.org#pdepend"
