language: php

matrix:
    include:
        - php: 5.3
          dist: precise
          env: DEPENDENCIES=low
        - php: 5.4
          env: DEPENDENCIES=low
        - php: 5.5
          env: SYMFONY_VERSION=^2.0
        - php: 5.6
          env: SYMFONY_VERSION=^2.0
        - php: 7.0
          env: SYMFONY_VERSION=^3.0
        - php: 7.1
          env: SYMFONY_VERSION=^4.0@RC
        - php: 7.2
          env: SYMFONY_VERSION=^4.0@RC
        - php: nightly
          env: SYMFONY_VERSION=^4.0@RC
    allow_failures:
      - php: nightly
    fast_finish: true

sudo: false

env:
    global:
        TEST_CONFIG="phpunit.xml.dist"

before_script:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/dependency-injection:${SYMFONY_VERSION}" --no-update; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/filesystem:${SYMFONY_VERSION}" --no-update; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/config:${SYMFONY_VERSION}" --no-update; fi;
    - if [ $DEPENDENCIES = low ] ; then composer update --prefer-dist --prefer-lowest --prefer-stable ; fi
    - if [ ! $DEPENDENCIES ] ; then composer update --prefer-dist ; fi
    - composer install

script:
    - vendor/bin/phpunit --configuration $TEST_CONFIG --colors --coverage-clover=coverage.xml
    - bash <(curl -s https://codecov.io/bash) -f coverage.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

notifications:
    irc: "irc.freenode.org#pdepend"
